### ISSUE TITLE
Does not work with Rails 4.2.0

### ISSUE THREAD

**Issue by jeffb-stell** [OceanDev/ocean-dynamo#17]
I think because of the pessimistic versioning on ActiveModel in the gemspec, I couldn't get this gem to work with rails 4.2.0.

I don't have a workaround (I downgraded to rails 4.1.8)

**Comment by jeffb-stell** [comment]
I lied, I ended up forking and removing the pessimistic versioning to get this working with 4.2.0 (because I was working with an existing app and downgrading wasn't working).

Code's at https://github.com/stelligent/ocean-dynamo.git . I'll update as/if I find any issues and fix them

**Comment by PeterBengtson** [comment]
Hi, thanks for notifying me. I haven’t even looked at Rails 4.2 yet, what with the holidays, but I will do so on Wednesday when I’m back at work.

	/ Peter
