### ISSUE TITLE
Do you have plans to support AWS-SDK version 2?

### ISSUE THREAD

**Issue by tikh** [OceanDev/ocean-dynamo#19]
Do you have plans to support AWS-SDK version 2?

**Comment by bramski** [comment]
+1.

**Comment by PeterBengtson** [comment]
There are definite plans of supporting AWS-SDK version 2. To be precise, it’s required in order to support multi-index tables, which will be required for certain relation types. So you can expect support for v2. Might happen sooner than you think, too. ;)

**Comment by bramski** [comment]
Cool.  Your project seems to be perhaps in conflict with the AWS rails-sdk though?

https://github.com/aws/aws-sdk-rails/issues/1

**Comment by PeterBengtson** [comment]
Yes. It'll be necessary to code directly against the AWS API.

**Comment by bramski** [comment]
You've closed this.  Was there an implementing change in this project?

**Comment by PeterBengtson** [comment]
No, but the question you put was answered, wasn't it? ;)

**Comment by bramski** [comment]
How terribly literal of you.  I'll open up a new issue to resolve when support for aws v2 is there.

**Comment by bramski** [comment]
https://github.com/OceanDev/ocean-dynamo/issues/22

**Comment by PeterBengtson** [comment]
Not being literal here at all, merely keeping things sorted. No need to open a ticket for it; it’s on the development schedule.
