### ISSUE TITLE
AWS SDK V2 support

### ISSUE THREAD

**Issue by bramski** [OceanDev/ocean-dynamo#22]
Currently this gem does not support AWS SDK V2.

**Comment by bramski** [comment]
The point is to close the issues when they are actually addressed.  Then people who look at this project can understand when it's been fixed.  I understand its on your schedule, but it's not done yet.  The idea would be for people to follow the issue, and they'd expect to see it closed when the support is released.  Otherwise how do others know about your internal schedule?

**Comment by PeterBengtson** [comment]
I'm only one person working on ocean-dynamo, and I do so when my work load permits and we need a specific new feature at my workplace. The point of internal schedules are that they are just that: internal. It's really impractical for me to commit to a specific schedule, especially a public one as it might interfere with my professional responsibilities.

Having said that, let me assure you that SDK v2 support is very high on my list as it's quite essential in many ways for the future development of ocean-dynamo. But it would be good if you let me create the enhancement tickets, as they essentially are working orders to myself. Questions and bug reports are of course always welcome.

Also, I do invite anyone to contribute to ocean-dynamo provided test coverage is at the same level or higher. In the case of AWS support, the entry barrier might be a little high as the code is quite abstract and compatibility with the internals of ActiveRecord is an important design goal.
