### ISSUE TITLE
Cost per request metrics

### ISSUE THREAD

**Issue by will3216** [OceanDev/ocean-dynamo#31]
I am currently evaluating DynamoDB as a solution to a high IO project on which I am about to start work. Before I do that, I need to understand the costs and benefits of the solution, as well as be able to manage the cost of the utility as the unit which will potentially be built on this technology scales. Given the transparent nature of the pricing structure of this DB, it seems to me that it would be relatively easy to calculate the cost of any given request to this datastore. Without putting any thought into naming, I am thinking something like this:
```
class MyModel < OceanDynamo::Table
  dynamo_schema(timestamps: [:created_at, :updated_at]) do
    attribute :some_attribute,   :string
    attribute :another_attribute,  :string
    attribute :data,          :string
    attribute :created_at,    :datetime
    attribute :updated_at,    :datetime

    global_secondary_index :some_attribute, projection: :all
    global_secondary_index :another_attribute, projection: :all
  end
end
```
Then:
```
> obj = MyModel.new(some_attribute: "foo", another_attribute: "bar", data: "This would be a field that holds the bulk of the object in some serialized form")
=> #<MyModel:0x007fe7b9dc9b98 @destroyed=false, @new_record=true, [...]>
> obj.changed? #easy to add parity to AR
=> true
> obj.units_per_second_to_save
=> 0.25 # Or whatever the math turns up with
```
Basically, I am looking for better a better way to understand the cost of an operation given the current conditions but more importantly I am looking for a way to monitor table utilization so that I don't have to worry about provisioning reads and writes and can just let the table sort itself out on its own without monitoring or incurring inefficient usage. I have a number of ideas on how to do this, but presently I am lacking any experience with the technology and could use some help thinking things through.

In addition, I have a bunch of suggestions, thoughts, and questions about this gem and this technology, and I'd love to talk if we could chat via email or some messaging service or just on here. Either way, I love what you've done with this, and I am more than willing to contribute! I just need more information on what you are hoping to accomplish with this gem and your thoughts/experience with this technology. Let me know!

**Comment by PeterBengtson** [comment]
This is a big topic. Usage patterns vary quite considerably from application to application, of course, and people approach the subject of setting quotas in different ways. I haven't really come across a case where it was necessary to compute and/or accumulate the cost for individual operations; rather, common practice seems to be quite the opposite: quotas are raised and lowered depending on anticipated load. 

Your suggested pattern is new to me: I haven't seen the need for calculations quite that fine-grained. Also, quotas are slightly elastic; DynamoDB will allow usage to exceed quota for a limited period of time before throttling or reporting errors.

Furthermore, changing a quota takes time which means you don't want to do it too often, and a single table may have different quotas for different indices which can further complicate things.

However, DynamoDB is fairly inexpensive, which means quotas can be set "with room to spare".

Currently, I'm working on autoscaling for Ocean. This requires quotas to be updated according to an external schedule. But use cases differ widely – which is a good thing – and thus it's almost impossible to give any general advice in this area.

**Comment by will3216** [comment]
After having done more research, this isn't as necessary as I thought given a variety of tools that help you autoscale the quotas, but I am still interested in exposing some data that would help you make better design decisions. For instance something like:
```ruby
> obj = MyModel.create(atr: 'val')
=> #<MyModel @atr='val'>
> obj.size
=> <size of record to be stored>
```
Mainly because the cost of reading and writing the object is tied directly to size of the object. If nothing else, you could always just expose size and consumed units values that are already provided in the API response attached to read and write operations. Not super hard to figure out though, so it would just be something that would be nice to have.
