### ISSUE TITLE
Namespace Table by Environment

### ISSUE THREAD

**Issue by will3216** [OceanDev/ocean-dynamo#32]
It might make sense to namespace tables based on the environment they are deployed in eg MyModel would have the tables my_models_development, my_models_qa, my_models_staging, my_models_production, and my_models_test

**Comment by PeterBengtson** [comment]
There's already provision made for that in the ocean-rails gem. The following is a standard idiom used throughout Ocean whenever a DynamoDB table is used:

```
  dynamo_schema(:id, table_name_suffix: Api.basename_suffix, 
                     create: Rails.env != "production") do
     ...
  end
```
The documentation for <tt>Api.basename_suffix</tt> and <tt>Api.adorn_basename</tt> reads as follows:

```
  #
  # Adds environment info to the basename, so that testing and execution in various combinations
  # of the Rails env and the Chef environment can be done without collision. 
  #
  # The chef_env will always be appended to the basename, since we never want to share queues 
  # between different Chef environments. 
  #
  # If the chef_env is 'dev' or 'ci', we must separate things as much as
  # possible: therefore, we add the local IP number and the Rails environment. 
  #
  # We also add the same information if by any chance the Rails environment isn't 'production'. 
  # This is a precaution; in staging and prod apps should always run in Rails production mode, 
  # but if by mistake they don't, we must prevent the production queues from being touched.
  #
  # If +suffix_only+ is true, the basename will be excluded from the returned string.
  #
```

There's a wealth of useful stuff in the <tt>ocean-rails</tt> gem; if you haven't checked it out, take a look at [http://www.rubydoc.info/github/OceanDev/ocean-rails/frames](url).

**Comment by will3216** [comment]
Hey Peter, I always seem to be one step behind you! I'll make sure to be more thorough before posting anymore issues. Thanks for the response!

**Comment by PeterBengtson** [comment]
No problem at all – you're pinpointing things which should be emphasised
more in the documentation anyway, so I'm grateful for your input.
