### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by will3216** [OceanDev/ocean-dynamo#33]
Here are a couple notes on running OceanDynamo locally:
1. On Mac you can use brew to manage the install and running of dynamodb local: 
```$ brew install dynamodb-local```
2.  Endpoint needs to be configured to point to the local dynamodb in an initializer:
```ruby
#ruby!/my_app/config/initializers/my_model_dynamo_setup.rb
if Rails.env.test? || Rails.env.development?
  endpoint = 'localhost:8000' # This is the default port for running dynamodb locally
  MyModel.dynamo_client = Aws::DynamoDB::Client.new(endpoint: endpoint)
  MyModel.dynamo_resource = Aws::DynamoDB::Resource.new(client: MyModel.dynamo_client)
  MyModel.establish_db_connection 
end
```
It might make sense to make this configurable via an environment variable, so this configuration doesn't have to be repeated across multiple models. Or perhaps a yaml file similar to how ActiveRecord databases are configured.

**Comment by PeterBengtson** [comment]
Ocean-dynamo already supports config via environment variables, something it inherits from the Ruby AWS-SDK DynamoDB interface. The variables are <tt>AWS_ACCESS_KEY_ID</tt>, <tt>AWS_SECRET_ACCESS_KEY</tt>, and <tt>AWS_REGION<tt>. That's all you need to set, but you can also follow any of the alternate setups here: 

http://docs.aws.amazon.com/sdkforruby/api/Aws/DynamoDB/Client.html

The initialisation sequence you're using in your example code is unnecessarily low-level; there should no longer be any need to set the <tt>dynamo_client</tt> and <tt>dynamo_resource</tt> explicitly, nor any reason to call <tt>establish_db_connection</tt>. 

Also take a look at how the <tt>ocean-rails</tt> gem sets up DynamoDB. It essentially builds on the environment variable paradigm, but also reads a YAML file in case env vars haven't been set. You'll find the code here:

https://github.com/OceanDev/ocean-rails/blob/master/config/initializers/_aws_config.rb

**Comment by will3216** [comment]
If you have 
```ruby
class MyModel < OceanDynamo::Table
  schema(connect: true) do 
    ...
  end
end
```
Your table object will already be instantiated with the configuration options that were present when the class definition was loaded.

**Comment by PeterBengtson** [comment]
I'm not quite sure I'm following you here. Could you elaborate a little?

**Comment by will3216** [comment]
With connect: true set, if the model is loaded before the initializer is called, it does not pick up the configuration changes.
```ruby
> class MyModel < OceanDynamo::Table; dynamo_schema(connect: true, create: true) {attribute :atr, :string}; end
=> "my_models"
> MyModel.dynamo_client.config.endpoint
=> #<URI::HTTPS:0x007fe6c5b58cf0 URL:https://dynamodb.us-east-1.amazonaws.com>
> Aws.config.update(endpoint: 'localhost:8000')
=> {:region=>"us-east-1", :endpoint=>"localhost:8000"}
> MyModel.dynamo_client.config.endpoint
=> #<URI::HTTPS:0x007fe6c5b58cf0 URL:https://dynamodb.us-east-1.amazonaws.com>
```

**Comment by PeterBengtson** [comment]
I'll have to look into that a bit more closely. You're setting up things in
a way I never do as I mostly use the facilities provided by ocean-rails for
initialisation, i.e. the code I linked to in my previous email.

**Comment by will3216** [comment]
Yeah, no worries. Just trying to point out edge-cases when I come across them as I imagine if someone ever had an issue with something like this, it would be very difficult to debug :)
