### ISSUE TITLE
unable to sign request without credentials set

### ISSUE THREAD

**Issue by nathantechie9** [OceanDev/ocean-dynamo#34]
I setup IAM to authenticate access to dynamodb. Does the gem still need to use credentials? The error is happening when trying to save the model.

**Comment by nathantechie9** [comment]
I had to set the aws credentials for aws sdk gem and in this gems aws file.

**Comment by PeterBengtson** [comment]
I'm sorry, I don't understand your question. This is hardly a ocean-dynamo issue as such, but an AWS usage question. Is there something in the syntax or the semantics of ocean-dynamo which you perceive as wrong or problematic?
