### ISSUE TITLE
Table not found

### ISSUE THREAD

**Issue by nathantechie9** [OceanDev/ocean-dynamo#37]
AWS SDK 2 needs the region set when creating the client. Otherwise, I can't find the tables in dynamodb. I will do a pull request to show you.

**Comment by PeterBengtson** [comment]
You might want to take a look at the standard AWS initialisation code in the ocean-rails gem. It sets ENV variables for this purpose, then provides additional logic to read init values from a config file in case ENV values aren't set. It's the standard way of initialising AWS clients in Ocean.

[https://github.com/OceanDev/ocean-rails/blob/master/config/initializers/_aws_config.rb](url)

Here's the code in its entirety:

`# Check if the ENV vars are set; if so, don't read any file
if (ENV['AWS_ACCESS_KEY_ID'].present? &&
    ENV['AWS_SECRET_ACCESS_KEY'].present? &&
    ENV['AWS_REGION'].present?)
  Aws.config
else

  # The is the example file
  ef = File.join(Rails.root, "config/aws.yml.example")

  # Only load AWS data if there is an example file
  if File.exists?(ef)

    # This is the tailored file, not under source control.
    f = File.join(Rails.root, "config/aws.yml")
    
    # If the tailored file doesn't exist, and we're running in test mode
    # (which is the case under TeamCity), use the example file as-is.
    unless File.exists?(f)
      f = ENV['OCEAN_API_HOST'] ? ef : false
    end

    # If there is a file to process, do so
    if f
      cfg = YAML.load(File.read(f))[Rails.env]
      # Set the ENV variables
      ENV['AWS_ACCESS_KEY_ID'] = cfg[:access_key_id] || cfg['access_key_id']
      ENV['AWS_SECRET_ACCESS_KEY'] = cfg[:secret_access_key] || cfg['secret_access_key']
      ENV['AWS_REGION'] = cfg[:region] || cfg['region']
      # Configure AWS with the raw cfg data
      AWS.config(cfg)
      # Configure Aws with a massaged version of the cfg data
      config = { region: ENV['AWS_REGION'],
                 credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'])
      }
      config[:endpoint] = cfg["endpoint"] if cfg["endpoint"]
      Aws.config.update(config)
    else
      # Otherwise print an error message and abort.
      puts
      puts "-----------------------------------------------------------------------"
      puts "AWS config file missing. Please copy config/aws.yml.example"
      puts "to config/aws.yml and tailor its contents to suit your dev setup."
      puts "Alternatively export environment variables AWS_ACCESS_KEY_ID,"
      puts "AWS_SECRET_ACCESS_KEY, and AWS_REGION."
      puts
      puts "NB: aws.yml is excluded from git version control as it will contain"
      puts "    data private to your Ocean system."
      puts "-----------------------------------------------------------------------"
      puts
      abort
    end
  end
end`

**Comment by nathantechie9** [comment]
Ok, thanks. Your solution makes sense. I just wasn't sure if the gem code loaded the ENV region var.
