### ISSUE TITLE
GSI projection

### ISSUE THREAD

**Issue by sdfsdfsdxx1** [OceanDev/ocean-dynamo#38]
Hi, I wonder if you support GSI projection :included. What is the right syntax for that?

Thank you.

**Comment by PeterBengtson** [comment]
GSI (Global Secondary Indices) in ocean-dynamo do not support the :included GSI projection. However, the finders for global secondary indices (find_global, find_global_each), if the :keys_only projection is chosen (the default), ocean-dynamo will perform a second read to fetch the whole record.
