### ISSUE TITLE
Rails 5.0 support

### ISSUE THREAD

**Issue by johan-smits** [OceanDev/ocean-dynamo#40]
When using the 1.3.0 version of the gem you can not use rails 5.0.
Are there plans to support it?

```
ocean-dynamo (~> 1.3) was resolved to 1.3.0, which depends on
      activesupport (~> 4)
```

**Comment by PeterBengtson** [comment]
Absolutely. I'd say that ocean-dynamo should be usable with 5.x as soon as
the dependency is updated. Functionally, things should be identical.

You can try forking the repo and changing the 4.x dependencies to 5.x
instead, if you're in a hurry.
tis 9 aug. 2016 kl. 11:28 skrev Johan Smits <notifications@github.com>:

**Comment by johan-smits** [comment]
Not in a hurry here, any eta when the dependencies will he changed?

**Comment by PeterBengtson** [comment]
Depends on when I get time to upgrade Ocean to 5.x. A little too early to
tell at the moment, but it has fairly high priority.
tis 9 aug. 2016 kl. 13:00 skrev Johan Smits <notifications@github.com>:

**Comment by PeterBengtson** [comment]
Rails 5.0.x is now supported. `ocean-dynamo` now runs under any Rails version from 4.0.0 to 5.0.x. Rails 5.1.0, which still is in beta, will require a few minor changes.
