### ISSUE TITLE
Creating new global_secondary_index on existing table

### ISSUE THREAD

**Issue by n00ge** [OceanDev/ocean-dynamo#41]
Does ocean-dynamo handle creating new global_secondary_indexes on existing tables? How do I do this? I'm currently running into this error:

```
Aws::DynamoDB::Errors::ValidationException: The table does not have the specified index: the_index_global
```

I have an existing schema created and just added a new line w/ the new global_secondary_index.

**Comment by PeterBengtson** [comment]
Ocean-dynamo will update the scheme unless this has been disabled. Check
the args, especially the :create one. If you're using the standard setup as
used in Ocean, the prod environment may be switched off. If this doesn't
help, let me see the code.

fre 2 sep. 2016 kl. 22:09 skrev Chad Calhoun <notifications@github.com>:
